version: 2
jobs: 
  build: 
    working_directory: ~/purescript-avro
    docker: 
      - image: circleci/node
    steps: 
      - checkout
      - run:
          name: update-yarn
          command: 'sudo npm install -g yarn'
      - restore_cache: 
          key: dependency-cache-{{ checksum "yarn.lock" }}
      - run:
          name: install-yarn-wee
          command: yarn install
      - save_cache: 
          key: dependency-cache-{{ checksum "yarn.lock" }}
          paths:
            - ./node_modules
      - run: # run tests
          name: test
          command: yarn test